import type { Metadata } from "next";
import { Imperial_Script, Inter } from "next/font/google";
import "./globals.css";

import { FireIcon } from "@/components/icons/fire-icon";

import { Navbar } from "@/components/common/navbar";
import Head from "next/head";

const inter = Inter({
  subsets: ["latin"],
  display: "auto",
});

export const metadata: Metadata = {
  title: "Dunails",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=Abhaya+Libre:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body className={`${inter.className} antialiased bg-white`}>
        <header>
          <div className="w-full py-2.5 bg-red-800 text-white flex items-center justify-center">
            <p className="font-medium text-base flex items-center gap-x-2.5">
              <FireIcon />
              Só este mês 20% de desconto em todos os serviços
              <FireIcon />
            </p>
          </div>
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
}
